pcd_path: <path to point cloud>
mesh_path: <path to mesh of inspection object>
output_directory: <directory in which the results are written>
visualize: True
do_remove_downward_normals: False
general:
  n_drones: 5
  nb_count: 3
  voxel_size: 2
open3d:
  camera_x: 0
  camera_y: -200
  width: 1000
  height: 1000
path_planning:
  p_start:
    - [ 0, 0, 0 ]
  d_min: 03
  d_max: 0.6
charging_optimization:
  charging_positions:
    - [ 0, 0, 0 ]
    - [ 1, 1, 0 ]
  B_min: 0.1
  B_max: 1
  B_start: 1
  v: 1
  r_charge: 0.02
  r_deplete: 0.006
  epsilon: 1
  schedule_delta: 10
  plot_delta: 1
  W: 25
  sigma: 1